apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: core-api
  namespace: aditi-stays
spec:
  selector:
    matchLabels:
      app: core-api
  namespaceSelector:
    matchNames:
      - aditi-stays
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chat-service
  namespace: aditi-stays
spec:
  selector:
    matchLabels:
      app: chat-service
  namespaceSelector:
    matchNames:
      - aditi-stays
  endpoints:
    - port: http
      path: /api/metrics
      interval: 30s
