apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: core-api
  namespace: aditi-stays
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: aditi-stays
$patch: delete
