apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: applications
resources:
  - ../base
  - ingress-alb.yaml
patches:
  - path: delete-base-namespace.yaml
  - path: delete-base-ingress.yaml
  - path: delete-pdb.yaml
  - path: delete-base-secret.yaml
  - path: patch-core-api.yaml
  - path: patch-chat-service.yaml
  - path: patch-frontend.yaml
  - path: patch-core-api-service.yaml
  - path: patch-chat-service-service.yaml
generatorOptions:
  disableNameSuffixHash: true
