apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: aditi-stays
spec:
  replicas: 1
  strategy:
    $patch: replace
    type: Recreate
  template:
    spec:
      affinity: {}
      containers:
        - name: frontend
          env:
            - name: NEXT_PUBLIC_CORE_API_URL
              value: ""
            - name: NEXT_PUBLIC_CHAT_HTTP_URL
              value: ""
            - name: NEXT_PUBLIC_CHAT_WS_URL
              value: ""
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
