apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: aditi-stays
spec:
  replicas: 1
  strategy:
    $patch: replace
    type: Recreate
  template:
    spec:
      containers:
        - name: chat-service
          env:
            - name: PUBLIC_BASE_URL
              value: ""
            - name: CORS_ALLOWED_ORIGINS
              value: "*"
            - name: BANNER_MAX_UPLOAD_SIZE_MB
              value: "20"
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "384Mi"
