apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: aditi-stays
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
    alb.ingress.kubernetes.io/success-codes: "200-399"
