apiVersion: v1
kind: ConfigMap
metadata:
  name: aditi-stays-config
  namespace: aditi-stays
data:
  CORE_API_PORT: "8080"
  CHAT_SERVICE_PORT: "8000"
  FRONTEND_PORT: "3000"
  CHAT_NOTIFICATION_CHANNEL: "lead_notifications"
