apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: core-api
  namespace: aditi-stays
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: core-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: aditi-stays
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
